### ISSUE TITLE
デプロイ時にfirebaseのホスティングが落ちる

### ISSUE THREAD

**Issue by YukiAmakawa** [misokatsu-web/official_site#2]
エラー内容

```
Error: Input required and not supplied: firebaseServiceAccount
    at Object.r.getInput (/home/runner/work/_actions/FirebaseExtended/action-hosting-deploy/v0/bin/action.min.js:1:3939)
    at Object.<anonymous> (/home/runner/work/_actions/FirebaseExtended/action-hosting-deploy/v0/bin/action.min.js:1:297680)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by 32moto** [comment]
不要な処理だったので削除
#3
